owner: calkit
name: example-basic
title: Basic Calkit example
description: A basic Calkit example project.
git_repo_url: https://github.com/calkit/example-basic

dependencies:
  - docker
  - uv

questions:
  - question: How does the system respond to increasing $x$?
    hypothesis: The value of $y$ increases linearly with $x$.
    answer: $y$ increases quadratically with $x$, not linearly.
    evidence:
      - kind: figure
        path: figures/x-vs-y.png
      - kind: result
        path: results/summary.json
        key: mean # r^2 for linear vs quadratic fit?

environments:
  py:
    path: requirements.txt
    kind: uv-venv
    python: "3.13"
    prefix: .venv
    description: A Python virtual environment managed with uv
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeX Live via Docker.

pipeline:
  stages:
    collect-data:
      kind: python-script
      script_path: scripts/collect-data.py
      environment: py
      outputs:
        - data/raw/data.csv
    plot-voltage:
      kind: python-script
      script_path: scripts/plot-voltage.py
      environment: py
      inputs:
        - from_stage_outputs: collect-data
      outputs:
        - figures/x-vs-y.png
        - results/summary.json
    figs-to-paper:
      kind: map-paths
      paths:
        - kind: dir-to-dir-replace
          src: figures
          dest: paper/figures
    results-to-tex:
      kind: json-to-latex
      inputs:
        - results/summary.json
      outputs:
        - paper/results.tex
    build-paper:
      kind: latex
      target_path: paper/paper.tex
      environment: tex
      inputs:
        - figures
        - paper/results.tex
      outputs:
        - paper/paper.pdf

datasets:
  - path: data/raw/data.csv
    title: Raw data
    description: This is raw voltage data.
    stage: collect-data

figures:
  - path: figures/x-vs-y.png
    title: Raw voltage time series
    description: A plot of the raw voltage time series.
    stage: plot-voltage

publications:
  - path: paper/paper.pdf
    title: The paper
    description: This is the paper.
    stage: build-paper

showcase:
  - publication: paper/paper.pdf

overleaf: {}

# This section describes how to use this project as a template for new projects
template: {}
